<?php

class MY_Loader extends CI_Loader {

    public function view($view, $vars = [], $return = false) {
        return parent::view($view, $vars, $return); // TODO: Change the autogenerated stub
    }
}