<?php

class MY_Loader extends CI_Loader{
    public function view($view, $vars = array(), $return = FALSE)
    {
        return parent::view($view, $vars, $return); // TODO: Change the autogenerated stub
    }
}